### ISSUE TITLE
Unable to view deployed app

### ISSUE THREAD

**Issue by pavithraes** [nebari-dev/jhub-apps#370]
### Context

I have a Streamlit App, deployed with JHub Apps with the following options:
- The file is in my personal file system
- Environment is in a shared (`analyst`) namespace
- Shared with users in the same `analyst` group

Users in the group can see the app in the Homescreen, but get the following error on opening it:

```python-traceback
Traceback (most recent call last):
  File "/opt/conda/envs/default/lib/python3.11/site-packages/tornado/web.py", line 1790, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/opt/conda/envs/default/lib/python3.11/site-packages/jhsingle_native_proxy/websocket.py", line 102, in get
    return await self.http_get(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/default/lib/python3.11/site-packages/jhsingle_native_proxy/proxyhandlers.py", line 849, in http_get
    return await self.proxy(self.port, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/default/lib/python3.11/site-packages/jhsingle_native_proxy/proxyhandlers.py", line 843, in proxy
    return await self.oauth_proxy(port, path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/default/lib/python3.11/site-packages/tornado/web.py", line 3298, in wrapper
    self.redirect(url)
  File "/opt/conda/envs/default/lib/python3.11/site-packages/jupyterhub/services/auth.py", line 1508, in raise_on_redirect
    raise HTTPError(
tornado.web.HTTPError: HTTP 403: Forbidden (user pavithraes+testingrereg@outlook.com is not allowed.)
```

### Value and/or benefit

Bug-fix

### Anything else?

I'm using JHub Apps on a deployed Nebari instance v2024.6.1

**Comment by aktech** [comment]
This was due to lack of permissions for the user. The required permissions to share with a group is:

```python
# can omit "read:users:name" if not sharing with user
shares,read:users:name,read:groups:name
```
