### ISSUE TITLE
[DOC] - Issues with Installing and Starting

### ISSUE THREAD

**Issue by jbouder** [nebari-dev/jhub-apps#4]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

I can't seem to get the app running locally by following the README steps. A few things:

1. The dependencies file name is incorrect, it should be `environment-dev.yml` (not `.yaml`)
2. After updating the above, I still receive the following error when I try to start JupyterHub:

```
Traceback (most recent call last):
      File "/opt/homebrew/lib/python3.11/site-packages/jupyterhub/app.py", line 3379, in launch_instance_async
        await self.initialize(argv)
      File "/opt/homebrew/lib/python3.11/site-packages/jupyterhub/app.py", line 2857, in initialize
        self.load_config_file(self.config_file)
      File "/opt/homebrew/lib/python3.11/site-packages/traitlets/config/application.py", line 113, in inner
        return method(app, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/lib/python3.11/site-packages/traitlets/config/application.py", line 950, in load_config_file
        for (config, fname) in self._load_config_files(
      File "/opt/homebrew/lib/python3.11/site-packages/traitlets/config/application.py", line 909, in _load_config_files
        config = loader.load_config()
                 ^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/lib/python3.11/site-packages/traitlets/config/loader.py", line 626, in load_config
        self._read_file_as_dict()
      File "/opt/homebrew/lib/python3.11/site-packages/traitlets/config/loader.py", line 659, in _read_file_as_dict
        exec(compile(f.read(), conf_filename, "exec"), namespace, namespace)  # noqa
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/.../repos/jhub-apps/jupyterhub_config.py", line 1, in <module>
        from jhub_apps.configuration import install_jhub_apps
    ModuleNotFoundError: No module named 'jhub_apps'
```

### Steps to Resolve this Issue

1. Follow steps indicated in the README
...

**Comment by aktech** [comment]
Hey @jbouder thanks for trying this out. This project is still in very early stage of development and docs are far from complete or even preliminary. I am working on it and hoping to add them by early next week.

**Comment by jbouder** [comment]
Made a little progress. Was able to load mostly up after using conda to install panel...which kind of makes sense.

**Comment by aktech** [comment]
I have updated the dependencies, let me know if it doesn't works now.

**Comment by aktech** [comment]
I have updated the readme, feel free to reopen if it doesn't works.
