### ISSUE TITLE
[ENH] - Support for windows (?)

### ISSUE THREAD

**Issue by aktech** [nebari-dev/jhub-apps#93]
### Feature description

Add/Test support for windows. This might not be possible without upstream changes, as per JupyterHub's docs:

> JupyterHub officially does not support Windows. You may be able to use JupyterHub on Windows if you use a Spawner and Authenticator that work on Windows, but the JupyterHub defaults will not. Bugs reported on Windows will not be accepted, and the test suite will not run on Windows. Small patches that fix minor Windows compatibility issues (such as basic installation) may be accepted, however. For Windows-based systems, we would recommend running JupyterHub in a docker container or Linux VM.

This could also mean writing a spawner/authenticator that works on windows.

Ref: https://jupyterhub.readthedocs.io/en/stable/tutorial/installation-basics.html#platform-support

Failing Integration tests on the CI: https://github.com/nebari-dev/jhub-apps/actions/runs/7704866443/job/20997894232

### Value and/or benefit

Ability to use this on windows.

### Anything else?

A quick test of this gives us the following blockers:

## 1.  In `uvicorn`: OSError: [WinError 10022] An invalid argument was supplied

We can (most likely) get away with this by increasing the number of workers.

```python
Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\envs\jhub-apps-dev\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\ProgramData\miniconda3\envs\jhub-apps-dev\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\miniconda3\envs\jhub-apps-dev\Lib\site-packages\uvicorn\_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "C:\ProgramData\miniconda3\envs\jhub-apps-dev\Lib\site-packages\uvicorn\server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\jhub-apps-dev\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\jhub-apps-dev\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\jhub-apps-dev\Lib\asyncio\base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\jhub-apps-dev\Lib\site-packages\uvicorn\server.py", line 79, in serve
    await self.startup(sockets=sockets)
  File "C:\ProgramData\miniconda3\envs\jhub-apps-dev\Lib\site-packages\uvicorn\server.py", line 129, in startup
    server = await loop.create_server(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\jhub-apps-dev\Lib\asyncio\base_events.py", line 1581, in create_server
    server._start_serving()
  File "C:\ProgramData\miniconda3\envs\jhub-apps-dev\Lib\asyncio\base_events.py", line 315, in _start_serving
    sock.listen(self._backlog)
OSError: [WinError 10022] An invalid argument was supplied
```

## 2.  `subprocess`: `ValueError: preexec_fn is not supported on Windows platforms`

We can get away with this by creating a custom spawner that doesn't depends on this (`preexec_fn`).

```python
[E 2024-01-30 14:04:13.154 JupyterHub web:1871] Uncaught exception POST /hub/api/users/admin/servers/panel-7cf34a2 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8081', method='POST', uri='/hub/api/users/admin/servers/panel-7cf34a2', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "C:\ProgramData\miniconda3\envs\jhub-apps-dev\Lib\site-packages\tornado\web.py", line 1786, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "C:\ProgramData\miniconda3\envs\jhub-apps-dev\Lib\site-packages\jupyterhub\apihandlers\users.py", line 558, in post
        await self.spawn_single_user(user, server_name, options=options)
      File "C:\ProgramData\miniconda3\envs\jhub-apps-dev\Lib\site-packages\jupyterhub\handlers\base.py", line 1078, in spawn_single_user
        await gen.with_timeout(
      File "C:\ProgramData\miniconda3\envs\jhub-apps-dev\Lib\site-packages\jupyterhub\handlers\base.py", line 988, in finish_user_spawn
        await spawn_future
      File "C:\ProgramData\miniconda3\envs\jhub-apps-dev\Lib\site-packages\jupyterhub\user.py", line 902, in spawn
        raise e
      File "C:\ProgramData\miniconda3\envs\jhub-apps-dev\Lib\site-packages\jupyterhub\user.py", line 798, in spawn
        url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\Administrator\jhub-apps\jhub_apps\spawner\spawner_creation.py", line 112, in start
        return await super().start()
               ^^^^^^^^^^^^^^^^^^^^^
      File "C:\ProgramData\miniconda3\envs\jhub-apps-dev\Lib\site-packages\jupyterhub\spawner.py", line 1699, in start
        self.proc = Popen(cmd, **popen_kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\ProgramData\miniconda3\envs\jhub-apps-dev\Lib\subprocess.py", line 844, in __init__
        raise ValueError("preexec_fn is not supported on Windows "
    ValueError: preexec_fn is not supported on Windows platforms

```

**Comment by aktech** [comment]
Relevant links:
- https://github.com/jupyterhub/jupyterhub/issues/1158
- https://github.com/ni/jupyterhub-winauthenticator
- https://github.com/ni/jupyterhub-winlocalprocessspawner

**Comment by aktech** [comment]
Closing as not relevant anymore
